name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration:
    uses: ansible-network/github_actions/.github/workflows/integration.yml@main
    with:
      network_os: cisco.nxos.nxos
      pytest_addopts: "-n auto --role-excludes=snmp_server"

    secrets:
      cml_ssh_password: ${{ secrets.cml_ssh_password }}
      virl_host: ${{ secrets.virl_host }}
      virl_password: ${{ secrets.virl_password }}
